### ISSUE TITLE
Mqtt interface

### ISSUE THREAD

**Issue by anthonyangel** [nathankellenicki/node-poweredup#105]
Hi, has anyone written some middleware to present an mqtt interface to control a connected device?

Alternatively is there a dashboard with a rest API?

**Comment by GianCann** [comment]
With the first version I haved used the Rest API (written from another guy) with Node-Red and MQTT.
I try to find the repository, but I'm not sure if it work also with the latest implementation of @nathankellenicki library.

**Comment by anthonyangel** [comment]
So far I've only found https://github.com/Ozafy/rocrail-mqtt-lego-powered-up

**Comment by GianCann** [comment]
What I found was a real http server that interfaced with nathan's library.
I'm trying to recover the info (these are experiments done a long time ago)

**Comment by GianCann** [comment]
I find it!
https://github.com/MihaZelnik/PoweredUp-REST-API

**Comment by GianCann** [comment]
@anthonyangel What's your project?

**Comment by anthonyangel** [comment]
@GianCann I'd like to control a Duplo train from [Home Assistant](https://www.home-assistant.io/) -  there's a couple of things I'm thinking of doing with it:
- Control via Google Home / Alexa
- Having the state of the train (e.g. when it runs over an action brick) trigger other hardware (so I can sync the train lights with a lifx bulb, or the speakers with a Sonos)

**Comment by GianCann** [comment]
😄  I also use Home Assistant ;)

**Comment by anthonyangel** [comment]
I figured that this is possible, so why not try. I'll work out properly what to do with it once it works!
