### ISSUE TITLE
Green value in ColorSensor / RGBLED don't match

### ISSUE THREAD

**Issue by cpseager** [nathankellenicki/node-poweredup#108]
Spot the difference 'green' in the color enums, from the Spike app source code.
Therefore they should not share the same @typedef Color

ColorSensor
e.black = "0"
e.violet = "1"
e.blue = "3"
e.azure = "4"
e.green = "5"
e.yellow = "7"
e.red = "9"
e.white = "10"
e.noColor = "-1"
e.changed = "-2"  

RGBLED
0 black
1 pink
2 violet
3 blue
4 azure
5 cyan
6 green
7 yellow
8 orange
9 red
10 white

**Comment by cpseager** [comment]
looks like Jorge also noticed this a while back https://github.com/JorgePe/BOOSTreveng/blob/master/ColorDistanceSensor.md

**Comment by corneliusmunz** [comment]
I faced the same issue in the legoino library: https://github.com/corneliusmunz/legoino/issues/43 I think thats a bug in the sensor firmware which will not be fixed. In the Lego PoweredUp app you can reproduce that issue with the following program. If you feed in directly the color sensor value to the HUB Led, the HUB LED will display CYAN if you detect a green brick. But if you read out only the color, the app will display green for a green brick. 
![IMG_7061](https://user-images.githubusercontent.com/8521596/102091123-aac65e00-3e1e-11eb-86cb-e65744b891c1.PNG)

**Comment by nathankellenicki** [comment]
I do recall this from a long time ago back when we originally started reverse engineering the protocol. I was hesitant to introduce two seperate enums, but I quite like @corneliusmunz 's solution for his library. I'll follow suit.

**Comment by nathankellenicki** [comment]
Implemented in v7.0.0
