### ISSUE TITLE
Getting hub object if you know hub uuid

### ISSUE THREAD

**Issue by MihaZelnik** [nathankellenicki/node-poweredup#11]
Is it possible to get hub object if you know hub uuid? 

So you do something like that, where you can get hubUuid from params for example?
```
hub = PUPHub(hubUuid);
hub.setLEDColor(1);
```

**Comment by nathankellenicki** [comment]
This should do what you want: https://github.com/nathankellenicki/node-poweredup#PoweredUP+getConnectedHubByUUID

**Comment by MihaZelnik** [comment]
Ah nice, totally missed that one :/

**Comment by MihaZelnik** [comment]
BTW awesome lib!

**Comment by nathankellenicki** [comment]
No problem, and thanks! :)

**Comment by MihaZelnik** [comment]
@nathankellenicki I did use your package and created REST API on top of it https://github.com/MihaZelnik/PoweredUp-REST-API/ (this is just a quick prototype for now so I know that it is possible)

Idea would be to have raspberry pi as a server so I can communicate with hubs via http and create some kind of web dashboard where I will be able to control it and make scenarios

**Comment by GianCann** [comment]
Hi, @nathankellenicki 
can you add a new method called getConnectedHubByName, that use friendly name configured by setName, instead of UUID?
