### ISSUE TITLE
Supporting more than 5 devices

### ISSUE THREAD

**Issue by MrShinyAndNew** [nathankellenicki/node-poweredup#122]
In my Linux-based setup, if I attempt to use more than 5 PU devices, things start to get weird. It appears that inputs from remotes continue to work, but outgoing commands to motors cease once the 6th hub is connected.

This may be a limit of the underlying BT hardware, but maybe not.

Request:
1. If possible, for a warning to be emitted if too many devices are connected, to help troubleshoot this problem.
2. A mechanism for using multiple BT adapters to control larger networks.

**Comment by nathankellenicki** [comment]
Hi, thanks for the comment. Unfortunately through previous experience, there are indeed varying numbers of supported devices per BT adapter, and there doesn't seem to be a way of getting feedback on how many are supported. It'll need to be trial and error. :(

Regarding the second request, this library uses the Noble BTLE library which doesn't seem to provide a mechanism to tell it which BTLE device to use. I believe this may be a limitation of the underlying bluez library, but I'm unsure.
