### ISSUE TITLE
Feature request: getConnectedHubByName

### ISSUE THREAD

**Issue by nathankellenicki** [nathankellenicki/node-poweredup#16]
Hi, @nathankellenicki 
can you add a new method called getConnectedHubByName, that use friendly name configured by setName, instead of UUID?

_Originally posted by @GianCann in https://github.com/nathankellenicki/node-poweredup/issues/11#issuecomment-459745886_

**Comment by nathankellenicki** [comment]
Hi @GianCann, I've added this in v1.8.0 which is now available. It is *almost* as you asked - getConnectedHubsByName (notice the plural), which returns an array of matching hubs. This is because multiple connected hubs can have the same name.

Hopefully this does what you need. :)

**Comment by GianCann** [comment]
ok, thank you very much!

**Comment by nathankellenicki** [comment]
Closed, fixed with 9ced6da24e2f45536d0253429542d73047a69efb
