### ISSUE TITLE
Is it possible to read tacho motor from a Control+ Smart hub?

### ISSUE THREAD

**Issue by jabrena** [nathankellenicki/node-poweredup#32]
Hi,

I would like to know if exist a way to read the tacho motor value from a Motor connected to a Control + Smart hub.

![image](https://user-images.githubusercontent.com/147263/67722512-91274480-f9d9-11e9-9370-4b58e55b4edd.png)

Many thanks in advance

Juan Antonio

**Comment by nutki** [comment]
I don't have one to test, but you should be able to do `cplushub.on("rotate", (port, position) => console.log(port, position))`.

**Comment by nathankellenicki** [comment]
Yep, you can check the rotation value by listening to "rotate" events. I'm still looking to implement a way of reading the angle from-zero.

**Comment by derammo** [comment]
that would be interesting if you can read angle from zero, since the motor acts like it doesn't have an absolute zero point (see #58)  

if you got this part to work, we could also implement setAbsolutePosition based on reading the current position, which would be sweet

**Comment by aileo** [comment]
Third mode of L/XL motors is `APOS` which I understand as "absolute position". You should be able to get this absolute position by listening to rotate event and subscribing to the motor with mode `0x03`.

**Comment by nathankellenicki** [comment]
That's correct. Absolute positioning is currently not fully supported, but hopefully soon. In the meantime you can use the existing mode.
