### ISSUE TITLE
can't install on raspbian 

### ISSUE THREAD

**Issue by romarro** [nathankellenicki/node-poweredup#5]
Hi I can't install it on raspbian because it can't find the noble-mac.git. Below is the error received
code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t https://github.com/Timeular/noble-mac.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

**Comment by nathankellenicki** [comment]
Please can you ensure you have git installed:

`sudo apt-get install git-core`

**Comment by romarro** [comment]
installing git-core fixed the problem. Thanks
