### ISSUE TITLE
Scanning for Hubs with 88006 and CSR8510 

### ISSUE THREAD

**Issue by Dmole** [nathankellenicki/node-poweredup#82]
The LED on my Bluetooth dongle will light up when I use bluetoothctl or gatttool (which successfully drives the Lego motors).

But when I run the example code it waits at "Scanning for Hubs..." forever and the LED on the dongle stays dark.

Maybe it's because the USB dongle has 2 Controllers, Any ideas how to make node-poweredup try more than the first Controller?

**Comment by nathankellenicki** [comment]
`node-poweredup` uses the Noble BLE library underneath to handle all its communications. I don't seen option for this per se, however if you can run your code again but with the environment variable `DEBUG=*` it should spit out some debug logging. I can then see if its a node-poweredup issue or a Noble issue.
