### ISSUE TITLE
Can´t connect with 42109

### ISSUE THREAD

**Issue by jujorie** [nathankellenicki/node-poweredup#85]
It discovers the hub as Undefined and does not continue with the connection

**Comment by nathankellenicki** [comment]
More info please, it's impossible to help without it. Hardware, OS, versions. Node.js or browser/Web Bluetooth? Also please set the `DEBUG=*` environment variable and provide the debug output when you try to connect.

**Comment by p8nut** [comment]
i just made an issue on the main abandonware/noble repo
https://github.com/abandonware/noble/issues/95
