### ISSUE TITLE
Add new motor types

### ISSUE THREAD

**Issue by cpseager** [nathankellenicki/node-poweredup#94]
Hi @nathankellenicki 

Thought you would be interested to know the latest spike app release adds
two new 'stonegrey' motor types 75/76, implemented identically to 48/49

So almost certainly the 51515 grey colour versions of the angular spike motors.

     e[e.HubVoltageSense = 20] = "HubVoltageSense",
     e[e.HubCurrentSense = 21] = "HubCurrentSense",
     e[e.HubUILight = 23] = "HubUILight",
     e[e.HubLEDMatrix = 25] = "HubLEDMatrix",
     e[e.WedoDetect = 35] = "WedoDetect",
     e[e.BoostVisionSensor = 37] = "BoostVisionSensor",
     e[e.BoostExternalEncodedMotor = 38] = "BoostExternalEncodedMotor",
     e[e.BoostInternalEncodedMotor = 39] = "BoostInternalEncodedMotor",
     e[e.BoostInternalTiltSensor = 40] = "BoostInternalTiltSensor",
     e[e.ConvoyLMotor = 46] = "ConvoyLMotor",
     e[e.ConvoyXLMotor = 47] = "ConvoyXLMotor",
     e[e.FlipperMediumMotor = 48] = "FlipperMediumMotor",
     e[e.FlipperLargeMotor = 49] = "FlipperLargeMotor",
     e[e.ThreeAxisAcceleration = 57] = "ThreeAxisAcceleration",
     e[e.ThreeAxisGyro = 58] = "ThreeAxisGyro",
     e[e.ThreeAxisOrientation = 59] = "ThreeAxisOrientation",
     e[e.TemperatureSensor = 60] = "TemperatureSensor",
     e[e.FlipperColor = 61] = "FlipperColor",
     e[e.FlipperDistance = 62] = "FlipperDistance",
     e[e.FlipperForce = 63] = "FlipperForce",
     e[e.RGBSensor = 64] = "RGBSensor",
     e[e.FlipperSmallMotor = 65] = "FlipperSmallMotor",
     e[e.StoneGreyMediumMotor = 75] = "StoneGreyMediumMotor",
     e[e.StoneGreyLargeMotor = 76] = "StoneGreyLargeMotor"

**Comment by nathankellenicki** [comment]
Interesting - thanks!

I think for the moment I'll hold off on implementing these. I'm not sure why there's a new device type/id if the motor is the same, just in a different color. Why would it be necessary for the software to be able to differentiate between the color of motor plugged in?

The new Mindstorms was announced this morning as coming out in Q4 2020, so when I get my hands on it I'll likely implement these. :)

**Comment by cpseager** [comment]
New colour = new part = new ID, I suppose

Every single motor bit of code has been modified like this, so pretty sure they are interchangeable. At least they won't take long to add!

     e.FlipperMediumMotor:
     e.StoneGreyMediumMotor:
      (do something)

     e.FlipperLargeMotor:
     e.StoneGreyLargeMotor:
     (do something)

**Comment by nathankellenicki** [comment]
Nice. The only reason I can think for a new LPF2 hub id if they're functionally the same is maybe they want the app UI to correctly reflect the motor you have plugged in - even with the correct color.

**Comment by nathankellenicki** [comment]
I changed my mind - I decided to add them. We can assume they're the same until we find out they aren't, and this means I hopefully don't need to remember to do it then.

Added in `v6.6.0`. Thanks!
